<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NodeStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeStateRepository extends EntityRepository
{
}
